### ISSUE TITLE
Class 'Hellotreedigital\Cms\Models\Language' not found 

### ISSUE THREAD

**Issue by vowval** [hellotreedigital/cms#15]
Class 'Hellotreedigital\Cms\Models\Language' not found (View: 
/vendor/hellotreedigital/cms/src/views/pages/cms-page/form.blade.php)
Kindly share how we can solve this issue

**Comment by hellotreedigital** [comment]
Updating the CMS to the latest version will solve the issue. If you have a database error after the update saying languages table is not available, please add the database table manually in the database
